title: ᴄᴏɴꜰɪɢᴜʀᴀ��ᴏ ᴅᴇ ʀᴇᴠɪꜱ�ᴏ
enabled_config: '<gray>ʜᴀʙɪʟɪᴛᴀᴅᴏ (ɴᴀ ᴄᴏɴꜰɪɢ)? %s'
revision_id:
  name: '<yellow>ɪᴅ ᴅᴇ ʀᴇᴠɪꜱ�ᴏ'
  lore:
    - '<gray>ᴏ ᴀᴛᴜᴀʟɪᴢᴀᴅᴏʀ ᴇꜱᴛᴀ ꜱᴇᴍᴘʀᴇ ᴀᴛɪᴠᴏ, ᴀᴜᴍᴇɴᴛᴀʀ'
    - '<gray>ᴇꜱᴛᴇ ɴ�ᴍᴇʀᴏ ᴀᴛᴜᴀʟɪᴢᴀʀ� ᴛᴏᴅᴀꜱ ᴀꜱ ɪɴꜱᴛ�ɴᴄɪᴀꜱ'
    - '<gray>ᴅᴇꜱᴛᴇ ᴍᴍᴏɪᴛᴇᴍ ꜱᴇᴍ ᴀ��ᴏ ᴀᴅɪᴄɪᴏɴᴀʟ.'
    - ''
    - '<gray>ᴠᴀʟᴏʀ ᴀᴛᴜᴀʟ: <yellow>%value%'
    - ''
    - '<yellow>ᴄʟɪǫᴜᴇ ᴘᴀʀᴀ ᴇᴅɪᴛᴀʀ'
toggles:
  keep_lore:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ʟᴏʀᴇ'
    lore:
      - '<gray>ᴍᴀɴᴛ�ᴍ ᴇꜱᴘᴇᴄɪꜰɪᴄᴀᴍᴇɴᴛᴇ ʟɪɴʜᴀꜱ ᴅᴇ ʟᴏʀᴇ ǫᴜᴇ ᴄᴏᴍᴇᴄᴀᴍ'
      - '<gray>ᴄᴏᴍ ᴏ ᴄᴏᴅɪɢᴏ ᴅᴇ ᴄᴏʀ'
  keep_name:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ɴᴏᴍᴇ'
    lore:
      - '<gray>ᴍᴀɴᴛ�ᴍ ᴏ ɴᴏᴍᴇ ᴅᴇ ᴇxɪʙɪ��ᴏ ᴅᴏ ɪᴛᴇᴍ.'
  keep_enchantments:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ᴇɴᴄᴀɴᴛᴀᴍᴇɴᴛᴏꜱ'
    lore:
      - '<gray>ɪꜱꜱᴏ ᴍᴀɴᴛ�ᴍ ᴇꜱᴘᴇᴄɪꜰɪᴄᴀᴍᴇɴᴛᴇ ᴇɴᴄᴀɴᴛᴀᴍᴇɴᴛᴏꜱ ǫᴜᴇ'
      - '<gray>ɴ�ᴏ ꜱ�ᴏ ᴄᴏɴᴛᴀʙɪʟɪᴢᴀᴅᴏꜱ ᴇᴍ ᴍᴇʟʜᴏʀɪᴀꜱ ɴᴇᴍ ɢᴇᴍᴀꜱ'
      - '<gray>(ᴘʀᴇꜱᴜᴍɪᴠᴇʟᴍᴇɴᴛᴇ ᴀᴅɪᴄɪᴏɴᴀᴅᴏꜱ ᴘᴇʟᴏ ᴊᴏɢᴀᴅᴏʀ).'
  keep_external_sh:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ꜱʜ ᴇxᴛᴇʀɴᴏ'
    lore:
      - '<gray>ᴅᴀᴅᴏꜱ ʀᴇɢɪꜱᴛʀᴀᴅᴏꜱ ɴᴀᴏ ꜱᴛᴀᴛʜɪꜱᴛᴏʀʏ ᴅᴏ ɪᴛᴇᴍ'
      - '<gray>ᴘᴏʀ ᴘʟᴜɢɪɴꜱ ᴇxᴛᴇʀɴᴏꜱ (ᴄᴏᴍᴏ'
      - '<gray>ɢᴇᴍꜱᴛᴏɴᴇꜱ ᴍᴀꜱ ɴᴀᴏ ʀᴇᴍᴏᴠ�ᴠᴇɪꜱ)'
  keep_upgrades:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ᴍᴇʟʜᴏʀɪᴀꜱ'
    lore:
      - '<gray>ᴇꜱᴛᴇ ɪᴛᴇᴍ ᴍᴀɴᴛᴇʀ� ᴏ ɴ�ᴠᴇʟ ᴅᴇ ᴍᴇʟʜᴏʀɪᴀ'
      - '<gray>ᴀᴘ�ꜱ ᴀ ᴀᴛᴜᴀʟɪᴢᴀ��ᴏ? ᴀᴘᴇɴᴀꜱ ᴏ ɴᴏᴠᴇʟ ᴅᴇ ᴍᴇʟʜᴏʀɪᴀ �'
      - '<gray>ᴍᴀɴᴛɪᴅᴏ (ᴅᴇꜱᴅᴇ ǫᴜᴇ ɴᴀᴏ ᴇxᴄᴇᴅᴀ ᴏ'
      - '<gray>ɴᴏᴠᴏ ᴍ�xɪᴍᴏ).'
  keep_gem_stones:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ɢᴇᴍᴀꜱ'
    lore:
      - '<gray>ᴏ ɪᴛᴇᴍ ᴍᴀɴᴛᴇʀ� ꜱᴜᴀꜱ ɢᴇᴍᴀꜱ ǫᴜᴀɴᴅᴏ'
      - '<gray>ᴀᴛᴜᴀʟɪᴢᴀʀ? (ɴᴏᴛᴇ ǫᴜᴇ ɪꜱꜱᴏ ᴘᴇʀᴍɪᴛᴇ ᴏᴠᴇʀꜰʟᴏᴡ ᴅᴇ ɢᴇᴍᴀꜱ'
      - '<gray>- ᴍᴀɴᴛᴇʀ� ᴛᴏᴅᴀꜱ ᴀꜱ ɢᴇᴍᴀꜱ ᴀɴᴛɪɢᴀꜱ'
      - '<gray>ᴍᴇꜱᴍᴏ ꜱᴇ ᴠᴏᴄᴇ ʀᴇᴅᴜᴢɪᴜ ᴏꜱ ꜱᴏᴄᴋᴇᴛꜱ ᴅᴇ ɢᴇᴍᴀꜱ)'
  keep_soulbind:
    name: '<yellow>ᴍᴀɴᴛᴇʀ ꜱᴏᴜʟʙɪɴᴅ'
    lore:
      - '<gray>ᴍᴀɴᴛ�ᴍ ᴏ ɴ�ᴠᴇʟ ᴇ ᴅᴀᴅᴏꜱ ᴅᴇ ꜱᴏᴜʟʙɪɴᴅ.'
