<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>me.ray.midgard</groupId>
        <artifactId>MidgardRPG</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>midgard-modules</artifactId>
    <packaging>pom</packaging>
    <name>midgard-modules</name>

    <!-- Dependências comuns herdadas por todos os módulos de gameplay -->
    <dependencies>
        <dependency>
            <groupId>dev.folia</groupId>
            <artifactId>folia-api</artifactId>
        </dependency>
        <dependency>
            <groupId>me.lucko</groupId>
            <artifactId>spark-api</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldedit</groupId>
            <artifactId>worldedit-bukkit</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sk89q.worldguard</groupId>
            <artifactId>worldguard-bukkit</artifactId>
        </dependency>
        <dependency>
            <groupId>me.clip</groupId>
            <artifactId>placeholderapi</artifactId>
        </dependency>
        <dependency>
            <groupId>com.comphenix.protocol</groupId>
            <artifactId>ProtocolLib</artifactId>
        </dependency>
        <dependency>
            <groupId>de.oliver</groupId>
            <artifactId>FancyHolograms</artifactId>
        </dependency>
        <dependency>
            <groupId>io.lumine</groupId>
            <artifactId>Mythic-Dist</artifactId>
        </dependency>
        <dependency>
            <groupId>de.oliver</groupId>
            <artifactId>FancyNpcs</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.NEZNAMY</groupId>
            <artifactId>TAB-API</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.MilkBowl</groupId>
            <artifactId>VaultAPI</artifactId>
        </dependency>
    </dependencies>

    <modules>
        <module>midgard-commands</module>
        <module>midgard-combat</module>
        <module>midgard-spells</module>
        <module>midgard-classes</module>
        <module>midgard-item</module>
        <module>midgard-mythicmobs</module>
        <module>midgard-essentials</module>
        <module>midgard-character</module>
        <module>midgard-security</module>
        <module>midgard-performance</module>
        <module>midgard-economy</module>
        <module>midgard-races</module>
        <module>midgard-professions</module>
    </modules>

</project>
